/**
 * Welcome to Cloudflare Workers! This is your first worker.
 *
 * - Run `npm run dev` in your terminal to start a development server
 * - Open a browser tab at http://localhost:8787/ to see your worker in action
 * - Run `npm run deploy` to publish your worker
 *
 * Learn more at https://developers.cloudflare.com/workers/
 */

export default {
  async fetch(request, env, ctx) {
    // Read the URL of the incoming request.
    const url = new URL(request.url);

    // This first version only handles the exact /secure path.
    if (url.pathname !== "/secure") {
      return new Response("Not found", {
        status: 404,
      });
    }

    // This is a temporary local page, not an authenticated response.
    const html = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>KaiOrderApp Worker</title>
  </head>
  <body>
    <h1>My first Worker page</h1>
    <p>This HTML was generated by my Worker.</p>
    <p>Authentication and private flags will be added next.</p>
  </body>
</html>`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "no-store",
      },
    });
  },
};